// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Api.Entities
{
    public partial class check_user_credentialsResult
    {
        public int? user_id { get; set; }
        public string password_hash { get; set; }
    }
}
