// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Api.Entities;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Api.Entities
{
    public partial interface Ishift_change_bdContextFunctions
    {
        Task<List<check_user_credentialsResult>> check_user_credentialsAsync(string p_email, CancellationToken cancellationToken = default);
    }
}
