// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Entities;

public partial class ShiftSwapRequest
{
    public int Id { get; set; }

    public int RequesterId { get; set; }

    public int TargetUserId { get; set; }

    public int RequesterShiftId { get; set; }

    public int TargetShiftId { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User Requester { get; set; }

    public virtual Shift RequesterShift { get; set; }

    public virtual Shift TargetShift { get; set; }

    public virtual User TargetUser { get; set; }
}