// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Api.Entities;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Api.Entities
{
    public partial class shift_change_bdContext
    {
        private Ishift_change_bdContextFunctions _procedures;

        public virtual Ishift_change_bdContextFunctions Functions
        {
            get
            {
                if (_procedures is null) _procedures = new shift_change_bdContextFunctions(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public Ishift_change_bdContextFunctions GetFunctions()
        {
            return Functions;
        }
    }

    public partial class shift_change_bdContextFunctions : Ishift_change_bdContextFunctions
    {
        private readonly shift_change_bdContext _context;

        public shift_change_bdContextFunctions(shift_change_bdContext context)
        {
            _context = context;
        }

        public virtual async Task<List<check_user_credentialsResult>> check_user_credentialsAsync(string p_email, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = "p_email",
                    Value = p_email ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Text,
                },
            };
            var _ = await _context.SqlQueryAsync<check_user_credentialsResult>("SELECT * FROM \"public\".\"check_user_credentials\" (@p_email)", npgsqlParameters, cancellationToken);

            return _;
        }
    }
}
