// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Entities;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string Role { get; set; }

    public virtual ICollection<ShiftSwapRequest> ShiftSwapRequestRequesters { get; set; } = new List<ShiftSwapRequest>();

    public virtual ICollection<ShiftSwapRequest> ShiftSwapRequestTargetUsers { get; set; } = new List<ShiftSwapRequest>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();
}